### ISSUE TITLE
Problem in linking to "individual" from another R package

### ISSUE THREAD

**Issue by slwu89** [mrc-ide/individual#75]
When following the instructions in the docs (https://mrc-ide.github.io/individual/articles/Performance.html#c-prefabs)  the resulting package cannot compile because it gets a "[type from individual] not declared in this scope" error. For some reason the header "individual.h" is not being included in the auto-generated RcppExports.cpp, so it doesn't see the type declarations. After finding out how to do it we will need to update the docs.

**Comment by giovannic** [comment]
Hmm, this does normally work. Our malaria model [has managed to link](https://github.com/mrc-ide/malariasimulation/blob/master/src/mosquito_emergence.cpp) to individual. It should be included automatically because of [individual_types](https://github.com/mrc-ide/individual/blob/master/inst/include/individual_types.h)

Some things to check:

 * What is the compiler commands so we could see the include directories?
 * What is the type that's missing?
 * Could you post the code which references the type?
 * Could you post the compiler error?

I agree the documentation needs to be improved here. I think an example package could be the way, [like the mockcpp vignette](https://github.com/mrc-ide/mockcpp/blob/master/vignettes/Examples.Rmd). I may have time to do that at the end of this week, it's quite finiky. But it does effectively show how the packages link.

**Comment by slwu89** [comment]
I did notice that just now! I'll use malarisimulation as a template and see where I'm going wrong. Since I need to do this anyway for another project which relies on individual, I can update the documentation as I get it worked out (especially since I have more of a "user's eye" view of the software).

Thanks for the hints, I'll get something working today/tomorrow.

**Comment by slwu89** [comment]
Thanks @giovannic, I forgot I needed to make a header file mypackage_types.hpp that includes the header from individual, so that Rcpp includes mypackage_types.hpp at the top of RcppExports.cpp. It all works now! I'll update the docs and search for some official Rcpp documentation on this to link to.

**Comment by giovannic** [comment]
oh yes!
